name: daangor
description: A project from 7Synco.com.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  flutter_svg: ^0.17.3+1
  flutter_staggered_grid_view: ^0.3.0
  sticky_headers: ^0.1.8
  datetime_picker_formfield: ^0.4.2
  curved_navigation_bar: ^0.3.0
  fluttertoast: ^3.1.3
  dio: ^3.0.9
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  google_maps_flutter: ^0.5.24+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

 


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "img/dangor.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - img/icon/
    - img/driver.png
    - img/index.jpg
    - img/onboarding1.png
    - img/onboarding2.png
    - img/onboarding3.jpg
    - img/twitter.png
    - img/facebook.png
    - img/google-plus.png
    - img/linkedin.png
    - img/slider1.png
    - img/slider2.jpg
    - img/slider3.jpg
    - img/user1.jpg
    - img/user2.jpg
    - img/user3.jpg
    - img/user0.jpg
    - img/visa.png
    - img/paypal.png
    - img/brazil.png
    - img/canada.png
    - img/china.png
    - img/france.png
    - img/germany.png
    - img/italy.png
    - img/netherlands.png
    - img/spain.png
    - img/united-arab-emirates.png
    - img/united-states-of-america.png
    - img/marker.png
    - img/colorado.jpg
    - img/chicagoTavel.jpg
    - img/paris.jpg
    - img/marriott.jpg
    - img/hilton.webp
    - img/coffeebar.jpg
    - img/coffeebar1.jpg
    - img/coffeebar3.jpeg
    - img/coffeebar4.jpg
    - img/gym.jpg
    - img/pizza.jpg
    - img/restaurent.jpg
    - img/mall.jpg
    - img/mall1.jpeg
    - img/elu.png
    - img/event1.jpg
    - img/event2.jpeg
    - img/event3.jpeg
    - img/event4.jpg
    - img/sport1.jpg
    - img/sport2.jpeg
    - img/car1.jpg
    - img/car2.jpg
    - img/car3.jpg
    - img/car4.jpg
    - img/jobs2.jpg
    - img/jobs3.jpg
    - img/gps.png
    - img/home_section_1.jpg
    - img/dark_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family:  ListingAppUI
     fonts:
      - asset: fonts/ListingAppUI.ttf
   - family:  IconMoon
     fonts:
      - asset: fonts/icomoon.ttf
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Thin.ttf
         weight: 100
       - asset: fonts/Poppins-ExtraLight.ttf
         weight: 200
       - asset: fonts/Poppins-Light.ttf
         weight: 300
       - asset: fonts/Poppins-Regular.ttf
         weight: 400
       - asset: fonts/Poppins-Medium.ttf
         weight: 500
       - asset: fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: fonts/Poppins-Bold.ttf
         weight: 700
       - asset: fonts/Poppins-ExtraBold.ttf
         weight: 800
       - asset: fonts/Poppins-Black.ttf
         weight: 900
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  